# Makefile for the Dijit controllers to extend HotDrink.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink-dijit

##################################################
# optional configuration

SRCDIR := lib
SOURCES := \
	slider.js \
	dijit.js

HEADERS := \
  lib/utility/debug.m4.js

